name: Provission AWS Resources with Terraform
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code to the ubuntu machine
        uses: actions/checkout@v4
        
      - name: Pull code from Repositories
        uses: hashicorp/setup-terraform@v3

      